name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Diğer adımlar (ör. npm install, test vs.)

      - name: Deploy to server
        run: |
          # Burada deploy komutlarınızı çalıştırın
          echo "Deploying to server..."
        env:
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
